enable_audio_bell no

font_family      FiraCode
bold_font        auto
italic_font      auto
bold_italic_font auto

disable_ligatures never

# Font size (in pts)
font_size 11.0

# Tokyo Night Moon
include theme.conf
include ${KITTY_OS}.conf
