# macOS-specific configuration

# Font settings for macOS
font-family = ""
font-family = "JetBrains Mono"
# font-family = "Iosevka Term"
# font-family = "Fira Code"

font-size = 13
adjust-cell-height = 2%
macos-titlebar-style = tabs
